### ISSUE TITLE
papara mail şablon çok lazım

### ISSUE THREAD

**Issue by stranos** [ahmetozalp/banka-otomotik-havale-odeme-onayi#1]
iyi günler hocam papara mail şablonu yapar mısınız lazım 
![image](https://user-images.githubusercontent.com/29098511/29778253-626c096e-8c17-11e7-8cfd-6f0ca2147647.png)

**Comment by ahmetozalp** [comment]
mailin kodlarını veya maili bana yonlendirme şansınvarsa ayarlarım 


iletisim@ahmetozalp.net

**Comment by stranos** [comment]
mail attım bekliyorum hocam teşekkürler şimdiden

**Comment by stranos** [comment]
mailim gelmiş mi hocam

**Comment by ahmetozalp** [comment]
gelmiş bayramdan sonra halletcem

**Comment by stranos** [comment]
tamam hocam sağolun merakla bekliyorum
